### ISSUE TITLE
build script doesnt work for 1.4 sagitta or 1.3 equuleus

### ISSUE THREAD

**Issue by mowoe** [runborg/vyos-pi-builder#16]
Hi!
first of all thank you for your work in this project. I have discovered some issues with the [build-image.sh](https://github.com/runborg/vyos-pi-builder/blob/master/build-image.sh) script:

1. `./configure` wont work in the `current` branch of `vyos-build`, as vyos discontinued using it (see [build docs](https://docs.vyos.io/en/latest/contributing/build-vyos.html) 'Build ISO'). The compilation and configuration process is now done by the `build-vyos-image` (python) script. To continue using this setup, the only possibility is to use vyos 1.3 (or lower) by checking out the `equuleus` branch during build.
2. The build script uses `data/generic-arm64.json` as the configuration for the build flavor. However, this file is not provided anywhere (anymore?), I had to create it myself. (This is true for both 1.4 and 1.3)

I already submitted PR #15 to fix a smaller issue and would be willing to contribute some more fixes for this project. However I think that the current project maintainers should decide how to continue on issue 1.), as the build scripts are currently not usable for vyos sagitta.

**Comment by runborg** [comment]
Hi @mowoe!

Thanks for wanting to participate on this project!
My main goal for this project was to get an initial version of vyos running on the pi, finding "bugs" and getting as much as the work possible upstreamed to the real vyos build repository. if a bug, inconcistancy or something else  is found in one or more build repos, i've made a workaround in this repo(if possible), sent pr's upstream and then removed the workaround here afterhand.

When i started working on this a arm64 build had as far as i know almost newer been attempted, at least not on the pi.
And because of this work all custom packages now have a working upstream arm64 deb package. but not all of them are verified working with its final config etc. eg. the kernel ++)

This work is done before the "big rewrite" of the vyos 1.4 build system, and after that i haven't had time to do any major work in this field.

then for part 1) i will happily merge versions of these scripts with a working commands for the new version of the vyos build system. these changes can include all kinds of "hotfixes" to the vyos-build repo needed for the build to succeed. My only limitation is that the hotfix should be able to be upstreamed to the orignal vyos-build repo in some form. eg. if we need a special config json file, create a working copy here, and then afterhand try to upstream the changes needed to the vyos-build repo

for 2) generic-arm64.json was the file describing properties used for doing the actual build in the old build-system, this file is now replaced with data/*.toml scripts. i suppose these ones should be used in some ways: /data/architectures/arm64.toml and /data/build-flavors/*, how this is specified at build time i do not know. 

To get a final understanding of how this is supposed to be used i think a study of how the new scripts/build-vyos-image is layed out is needed. hints will be provided there on what parameters etc. are needed to get a build running

Please feel free to submit pr's to fix up these issues. if you need to have a chat i and many others are available in the vyos slack chat in channel #vyos-on-arm64 and will gladly answer questions :)

Cheers, 
Runar

**Comment by mowoe** [comment]
Hi,

thank you for your explanation! To be honest, i dont know if i can make any useful contributions. I couldnt get a successful arm image built yet ^^ 
If I make some building 1.4 on arm, I'll try to contribute them.
