### ISSUE TITLE
make iso error

### ISSUE THREAD

**Issue by stormanger** [runborg/vyos-pi-builder#7]
Hi, 

When I trying to build an image I hit the following error:

```
xorriso 1.5.2 : RockRidge filesystem manipulator, libburnia project.

xorriso : NOTE : Environment variable SOURCE_DATE_EPOCH encountered with value 1647449038
Drive current: -outdev 'stdio:live-image-arm64.hybrid.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 62.2g free
xorriso : NOTE : -as mkisofs: Ignored option '-cache-inodes'
xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
Added to ISO image: directory '/'='/binary'
xorriso : UPDATE :     244 files added in 1 seconds
xorriso : FAILURE :  Cannot find in ISO image: -boot_image ... bin_path='/isolinux/isolinux.bin'
xorriso : UPDATE :     244 files added in 1 seconds
xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE'
E: An unexpected failure occurred, exiting...
P: Begin unmounting filesystems...
P: Saving caches... 
```

Can you please tell me where is the "boot_image ISO image" file is? How to complete the missing file?

Thanks

**Comment by runborg** [comment]
Hi stormanger! Could you please provide a pastebin with all commands executed and cli output from the complete build process?
as isolinux is x86 only it should be disabled in the build process when building on arm64

**Comment by stormanger** [comment]
Hi, runborg, 

Thanks for your help,
Follow is the pastebin: https://pastebin.com/fv0Kqg8T

I config the data/defaults.json file like that
```
# cat data/defaults.json
{
  "architecture": "arm64",
  "debian_mirror": "http://deb.debian.org/debian",
  "debian_security_mirror": "http://deb.debian.org/debian",
  "debian_distribution": "bullseye",
  "vyos_mirror": "http://dev.packages.vyos.net/repositories/current",
  "vyos_branch": "current",
  "kernel_version": "5.10.105",
  "kernel_flavor": "v8-arm64-vyos",
  "release_train": "sagitta",
  "bootloaders": "syslinux,grub-efi",
  "additional_repositories": [
        "deb [arch=arm64] http://repo.powerdns.com/debian bullseye-rec-45 main",
        "deb [arch=arm64] https://repos.influxdata.com/debian bullseye stable"
  ],
  "custom_packages": []
}
```

My commands is: 
./configure --architecture arm64
make iso

**Comment by runborg** [comment]
For the first, when you post an issue related to my code i suspect the issue should be related to my code or some code used in it. As it seems for me you are not using the code in this repository at all.. 

But, back to your issue... For the first, there is a perfectly fine json for building on arm64 in the vyos/vyos-build repository itself. it is also used in this repository to build. take a look in my build-image.sh for more information.
To use this json, do these build instructions:  (these instructions are buildable on a unmodified vyos-build repository)
```
VYOS_BUILD_FLAVOR=data/generic-arm64.json ./configure
make iso
```

The specific issue you are experiensing is because of this line:   `"bootloaders": "syslinux,grub-efi",` this line specifies that you should build the image with syslinux, but as syslinux is x86 only this will not work and xorriso fails because of this. look in the vyos-build/dara/generic-arm64.json for a working list of bootloaders..

**Comment by stormanger** [comment]
Hi, runborg,

Thanks for your help, 
I just referenced some of your practices, which gave me a lot of inspiration;
I have re-tested your code and it works fine;

Thanks for your help!
Best wishes
